### PR TITLE
Version increased to 0.4.5

### PR DESCRIPTION
**Pull request by Mikulas**

### CODE REVIEW

**Comment by chrisdaish** [comment]
Thanks @Mikulas, were you able to get the Docker image to build?

**Comment by Mikulas** [comment]
Turns out that it just failed on missing cabal >=1.8 :/ I will look into that.

**Comment by Mikulas** [comment]
@chrisdaish I've managed to build the image with newer Cabal. It's quite involved, feel free to close this PR if it complicates this project too much.

**Comment by chrisdaish** [comment]
Closing PR. Ill address the Cabal version issue when I rebase this to work from an Alpine base image.

**Pull request closed without merging**
